//	List of Words

var listOfWords = ["LOSANGELES","SANDIEGO","SANJOSE","SANFRANCISCO","FRESNO","SACRAMENTO",
"LONGBEACH","OAKLAND","BAKERSFIELD","ANAHEIM","PALOALTO","RIVERSIDE","SANTABARBARA",
"IRVINE","FREMONT","SANBERNARDINO","MOUNTAINVIEW","FONTANA","STOCKTON","MORENOVALLEY",
"GLENDALE","HUNTINGTONBEACH","SANTACLARITA","OCEANSIDE","SUNNYVALE","POMONA",
"ESCONDIDO","TORRANCE","PASADENA","MALIBU","MONTEREY","REDDING","CARLSBAD"];


module.exports = listOfWords;